# Booking Conversation Steps Configuration
# Defines the flow and validation for each step

steps:
  greeting:
    description: "Initial contact - detect language and greet"
    next_step: name
    actions:
      - detect_language
      - send_greeting
    
  name:
    description: "Collect customer name"
    next_step: goal
    validation:
      min_length: 2
      max_length: 100
    retry_message:
      en: "I didn't catch your name. What should I call you?"
      es: "No entendí tu nombre. ¿Cómo te llamas?"
    
  goal:
    description: "Understand business goals"
    next_step: pain
    validation:
      min_length: 5
      max_length: 200
    retry_message:
      en: "Could you tell me more about your business goals?"
      es: "¿Podrías contarme más sobre tus objetivos de negocio?"
    
  pain:
    description: "Identify pain points/challenges"
    next_step: budget
    validation:
      min_length: 5
      max_length: 200
    retry_message:
      en: "What specific challenges are you facing?"
      es: "¿Qué desafíos específicos estás enfrentando?"
    
  budget:
    description: "Qualify budget (minimum $300)"
    next_step: email  # or 'complete' if budget < 300
    validation:
      type: number
      minimum: 300
    below_minimum_message:
      en: "I appreciate your interest! We work with businesses investing at least $300/month in marketing. Feel free to reach out when you're ready to invest in growth."
      es: "¡Aprecio tu interés! Trabajamos con negocios que invierten al menos $300/mes en marketing. No dudes en contactarnos cuando estés listo para invertir en crecimiento."
    
  email:
    description: "Collect email for appointment details"
    next_step: day
    validation:
      type: email
      regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    retry_message:
      en: "Please provide a valid email address."
      es: "Por favor proporciona un correo electrónico válido."
    
  day:
    description: "Select preferred day"
    next_step: time
    validation:
      allowed_days:
        en: ["Tuesday", "Wednesday", "Thursday", "Friday"]
        es: ["Martes", "Miércoles", "Jueves", "Viernes"]
    retry_message:
      en: "Please choose between Tuesday and Friday."
      es: "Por favor elige entre Martes y Viernes."
    
  time:
    description: "Select appointment time"
    next_step: scheduled
    validation:
      must_be_available_slot: true
    retry_message:
      en: "That time isn't available. Please choose from the available slots."
      es: "Ese horario no está disponible. Por favor elige de los horarios disponibles."
    
  scheduled:
    description: "Appointment confirmed"
    next_step: complete
    is_terminal: true
    
  complete:
    description: "Conversation ended"
    is_terminal: true