business:
  name: "FitLife Coaching"
  minimum_budget: 1000
  timezone: "PST"
  appointment_duration: 30
  business_hours:
    monday: "9:00-18:00"
    tuesday: "9:00-18:00"
    wednesday: "9:00-18:00"
    thursday: "9:00-18:00"
    friday: "9:00-18:00"
    saturday: "10:00-16:00"
    sunday: "closed"