# GoHighLevel Custom Fields Configuration
# These fields must be created in GHL for the booking system to work

conversation_state:
  booking_step:
    type: dropdown
    options:
      - greeting
      - name
      - goal
      - pain
      - budget
      - email
      - day
      - time
      - scheduled
      - complete
    default: greeting
    
  language:
    type: dropdown
    options:
      - en
      - es
    default: en

customer_data:
  customer_name:
    type: text
    max_length: 100
    
  customer_goal:
    type: text
    max_length: 200
    description: "Business goals/objectives"
    
  customer_pain_point:
    type: text
    max_length: 200
    description: "Main challenges/pain points"
    
  customer_budget:
    type: number
    min: 0
    description: "Monthly marketing budget in USD"
    
  customer_email:
    type: email
    required_for_booking: true

booking_data:
  preferred_day:
    type: text
    max_length: 20
    
  preferred_time:
    type: text
    max_length: 20
    
  appointment_id:
    type: text
    description: "GHL calendar appointment ID"
    
  appointment_datetime:
    type: datetime
    description: "Scheduled appointment time"

metadata:
  booking_attempts:
    type: number
    default: 0
    description: "Number of booking attempts"
    
  last_interaction:
    type: datetime
    auto_update: true
    description: "Last webhook interaction timestamp"
    
  conversation_started:
    type: datetime
    description: "First interaction timestamp"